/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LeadResponse { 
    id?: string;
    tier?: LeadResponseTierEnum;
    message?: string;
    calendarRequired?: boolean;
}
export enum LeadResponseTierEnum {
    Low = 'LOW',
    Mid = 'MID',
    High = 'HIGH'
};



