/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SaasDetailsRequest } from './saasDetailsRequest';
import { WebsiteDetailsRequest } from './websiteDetailsRequest';
import { WebappDetailsRequest } from './webappDetailsRequest';


export interface LeadRequest { 
    projectType: LeadRequestProjectTypeEnum;
    businessName: string;
    industry: string;
    stage: LeadRequestStageEnum;
    websiteDetails?: WebsiteDetailsRequest;
    webappDetails?: WebappDetailsRequest;
    saasDetails?: SaasDetailsRequest;
    timeline: LeadRequestTimelineEnum;
    budgetRange: string;
    fullName: string;
    email: string;
    phone?: string;
    notes?: string;
    consentGiven: boolean;
    sourcePage?: string;
    utmSource?: string;
    utmMedium?: string;
    utmCampaign?: string;
    utmTerm?: string;
    utmContent?: string;
}
export enum LeadRequestProjectTypeEnum {
    Website = 'WEBSITE',
    Webapp = 'WEBAPP',
    Saas = 'SAAS',
    Unsure = 'UNSURE'
};
export enum LeadRequestStageEnum {
    JustStarting = 'JUST_STARTING',
    Established = 'ESTABLISHED',
    GoingDigital = 'GOING_DIGITAL',
    AlreadyOnline = 'ALREADY_ONLINE'
};
export enum LeadRequestTimelineEnum {
    Asap = 'ASAP',
    OneToThreeMonths = 'ONE_TO_THREE_MONTHS',
    ThreeToSixMonths = 'THREE_TO_SIX_MONTHS',
    SixToTwelveMonths = 'SIX_TO_TWELVE_MONTHS',
    NoRush = 'NO_RUSH'
};



