/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SaasDetails } from './saasDetails';
import { WebappDetails } from './webappDetails';
import { WebsiteDetails } from './websiteDetails';


export interface LeadDetailResponse { 
    id?: string;
    projectType?: LeadDetailResponseProjectTypeEnum;
    leadTier?: LeadDetailResponseLeadTierEnum;
    status?: LeadDetailResponseStatusEnum;
    businessName?: string;
    industry?: string;
    stage?: LeadDetailResponseStageEnum;
    timeline?: LeadDetailResponseTimelineEnum;
    budgetRange?: string;
    fullName?: string;
    email?: string;
    phone?: string;
    notes?: string;
    consentGiven?: boolean;
    consentAt?: string;
    sourcePage?: string;
    utmSource?: string;
    utmMedium?: string;
    utmCampaign?: string;
    utmTerm?: string;
    utmContent?: string;
    submittedAt?: string;
    contactedAt?: string;
    closedAt?: string;
    internalNotes?: string;
    websiteDetails?: WebsiteDetails;
    webappDetails?: WebappDetails;
    saasDetails?: SaasDetails;
}
export enum LeadDetailResponseProjectTypeEnum {
    Website = 'WEBSITE',
    Webapp = 'WEBAPP',
    Saas = 'SAAS',
    Unsure = 'UNSURE'
};
export enum LeadDetailResponseLeadTierEnum {
    Low = 'LOW',
    Mid = 'MID',
    High = 'HIGH'
};
export enum LeadDetailResponseStatusEnum {
    New = 'NEW',
    Contacted = 'CONTACTED',
    Qualified = 'QUALIFIED',
    ProposalSent = 'PROPOSAL_SENT',
    Won = 'WON',
    Lost = 'LOST',
    Spam = 'SPAM'
};
export enum LeadDetailResponseStageEnum {
    JustStarting = 'JUST_STARTING',
    Established = 'ESTABLISHED',
    GoingDigital = 'GOING_DIGITAL',
    AlreadyOnline = 'ALREADY_ONLINE'
};
export enum LeadDetailResponseTimelineEnum {
    Asap = 'ASAP',
    OneToThreeMonths = 'ONE_TO_THREE_MONTHS',
    ThreeToSixMonths = 'THREE_TO_SIX_MONTHS',
    SixToTwelveMonths = 'SIX_TO_TWELVE_MONTHS',
    NoRush = 'NO_RUSH'
};



