/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LeadSummaryResponse { 
    id?: string;
    projectType?: LeadSummaryResponseProjectTypeEnum;
    leadTier?: LeadSummaryResponseLeadTierEnum;
    status?: LeadSummaryResponseStatusEnum;
    businessName?: string;
    industry?: string;
    fullName?: string;
    email?: string;
    timeline?: LeadSummaryResponseTimelineEnum;
    budgetRange?: string;
    submittedAt?: string;
}
export enum LeadSummaryResponseProjectTypeEnum {
    Website = 'WEBSITE',
    Webapp = 'WEBAPP',
    Saas = 'SAAS',
    Unsure = 'UNSURE'
};
export enum LeadSummaryResponseLeadTierEnum {
    Low = 'LOW',
    Mid = 'MID',
    High = 'HIGH'
};
export enum LeadSummaryResponseStatusEnum {
    New = 'NEW',
    Contacted = 'CONTACTED',
    Qualified = 'QUALIFIED',
    ProposalSent = 'PROPOSAL_SENT',
    Won = 'WON',
    Lost = 'LOST',
    Spam = 'SPAM'
};
export enum LeadSummaryResponseTimelineEnum {
    Asap = 'ASAP',
    OneToThreeMonths = 'ONE_TO_THREE_MONTHS',
    ThreeToSixMonths = 'THREE_TO_SIX_MONTHS',
    SixToTwelveMonths = 'SIX_TO_TWELVE_MONTHS',
    NoRush = 'NO_RUSH'
};



