/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SaasDetails { 
    newOrRebuild?: SaasDetailsNewOrRebuildEnum;
    validationStage?: SaasDetailsValidationStageEnum;
    yearOneCustomers?: string;
    multiTenant?: SaasDetailsMultiTenantEnum;
}
export enum SaasDetailsNewOrRebuildEnum {
    New = 'NEW',
    Rebuild = 'REBUILD'
};
export enum SaasDetailsValidationStageEnum {
    NoValidation = 'NO_VALIDATION',
    Talking = 'TALKING',
    Waitlist = 'WAITLIST',
    Paying = 'PAYING'
};
export enum SaasDetailsMultiTenantEnum {
    Yes = 'YES',
    No = 'NO',
    Unsure = 'UNSURE'
};



