/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateLeadRequest { 
    status?: UpdateLeadRequestStatusEnum;
    internalNotes?: string;
}
export enum UpdateLeadRequestStatusEnum {
    New = 'NEW',
    Contacted = 'CONTACTED',
    Qualified = 'QUALIFIED',
    ProposalSent = 'PROPOSAL_SENT',
    Won = 'WON',
    Lost = 'LOST',
    Spam = 'SPAM'
};



