/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WebappDetails { 
    problemStatement?: string;
    userType?: WebappDetailsUserTypeEnum;
    features?: Array<string>;
}
export enum WebappDetailsUserTypeEnum {
    Single = 'SINGLE',
    Team = 'TEAM',
    Customers = 'CUSTOMERS',
    MultiTenant = 'MULTI_TENANT'
};



