/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WebsiteDetails { 
    hasExistingSite?: boolean;
    pageCount?: WebsiteDetailsPageCountEnum;
    features?: Array<string>;
}
export enum WebsiteDetailsPageCountEnum {
    OneToThree = 'ONE_TO_THREE',
    FiveToSeven = 'FIVE_TO_SEVEN',
    TenPlus = 'TEN_PLUS',
    Unsure = 'UNSURE'
};



